mkdir -p /mnt/mongo-data/
mkdir -p /mnt/mongo-data/config-1
mkdir -p /mnt/mongo-data/config-1/journal
mkdir -p /mnt/mongo-data/config-2
mkdir -p /mnt/mongo-data/config-2/journal
mkdir -p /mnt/mongo-data/config-3
mkdir -p /mnt/mongo-data/config-3/journal
mkdir -p /mnt/mongo-data/mongodb-s1-1
mkdir -p /mnt/mongo-data/mongodb-s1-1/journal
mkdir -p /mnt/mongo-data/mongodb-s1-2
mkdir -p /mnt/mongo-data/mongodb-s1-2/journal
mkdir -p /mnt/mongo-data/mongodb-s1-3
mkdir -p /mnt/mongo-data/mongodb-s1-3/journal
mkdir -p /mnt/mongo-data/mongodb-s2-1
mkdir -p /mnt/mongo-data/mongodb-s2-1/journal
mkdir -p /mnt/mongo-data/mongodb-s2-2
mkdir -p /mnt/mongo-data/mongodb-s2-2/journal
mkdir -p /mnt/mongo-data/mongodb-s2-3
mkdir -p /mnt/mongo-data/mongodb-s2-3/journal
mkdir -p /mnt/mongo-data/mongos-1
